name: Build API 1
on:
  push:
    branches:
      - main
    paths:
      - 'WebApplication1/**'
      - '.github/workflows/build-api1.yml'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ONSSecrets
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}

      - name: Build and push WebApplication1 image
        uses: docker/build-push-action@v4
        with:
          context: ./WebApplication1
          file: ./WebApplication1/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERUSERNAME }}/webapi:latest